DROP TABLE IF EXISTS PERSONA;

CREATE TABLE "PERSONA" (

    "ID"  VARCHAR2(6) NOT NULL PRIMARY KEY,
    "uUSER_NAME" VARCHAR2(20) NOT NULL,
    "APELLIDO" VARCHAR2(20),
    "TELEFONO" NUMBER,
    "EMAIL"  VARCHAR2(20) NOT NULL
);